steps:
  - name: Install Node.js dependencies
    run: npm install
    description: Install all required npm packages including express, sqlite3, and body-parser

  - name: Start development server
    run: npm run dev
    description: Start the server with nodemon for auto-reloading during development. The server will be available at http://localhost:3000

  - name: Verify server is running
    run: |
      echo "Waiting for server to start..."
      for i in {1..10}; do
        sleep 1
        if curl -f http://localhost:3000 > /dev/null 2>&1; then
          echo "✅ Server is running!"
          exit 0
        fi
      done
      echo "❌ Server failed to start after 10 seconds"
      exit 1
    description: Check that the development server started successfully with retry mechanism
